defmodule OMQ do
  @moduledoc false

  def context, do: call(:context, [])
  def context(io_threads), do: call(:context, [io_threads])
  def term(context), do: call(:term, [context])
  def socket(context, type), do: call(:socket, [context, type])
  def bind(socket, endpoint), do: call(:bind, [socket, endpoint])
  def bind_to_random_port(socket, addr), do: call(:bind_to_random_port, [socket, addr])

  def bind_to_random_port(socket, addr, min_port, max_port),
    do: call(:bind_to_random_port, [socket, addr, min_port, max_port])

  def connect(socket, endpoint), do: call(:connect, [socket, endpoint])
  def unbind(socket, endpoint), do: call(:unbind, [socket, endpoint])
  def disconnect(socket, endpoint), do: call(:disconnect, [socket, endpoint])
  def monitor(socket), do: call(:monitor, [socket])
  def monitor_recv(monitor), do: call(:monitor_recv, [monitor])
  def monitor_recv(monitor, timeout), do: call(:monitor_recv, [monitor, timeout])
  def monitor_try_recv(monitor), do: call(:monitor_try_recv, [monitor])
  def connections(socket), do: call(:connections, [socket])
  def connection_info(socket, connection_id), do: call(:connection_info, [socket, connection_id])
  def send(socket, data), do: call(:send, [socket, data])
  def send(socket, data, opts), do: call(:send, [socket, data, opts])
  def try_send(socket, data), do: call(:try_send, [socket, data])
  def try_send(socket, data, opts), do: call(:try_send, [socket, data, opts])
  def send_multipart(socket, parts), do: call(:send_multipart, [socket, parts])
  def send_multipart(socket, parts, opts), do: call(:send_multipart, [socket, parts, opts])
  def recv(socket), do: call(:recv, [socket])
  def recv(socket, timeout), do: call(:recv, [socket, timeout])
  def recv_frame(socket), do: call(:recv_frame, [socket])
  def recv_frame(socket, timeout), do: call(:recv_frame, [socket, timeout])
  def try_recv(socket), do: call(:try_recv, [socket])
  def recv_multipart(socket), do: call(:recv_multipart, [socket])
  def recv_multipart(socket, timeout), do: call(:recv_multipart, [socket, timeout])
  def try_recv_multipart(socket), do: call(:try_recv_multipart, [socket])
  def poll(entries, timeout), do: call(:poll, [entries, timeout])
  def select(rlist, wlist, xlist, timeout), do: call(:select, [rlist, wlist, xlist, timeout])
  def proxy(frontend, backend), do: call(:proxy, [frontend, backend])
  def proxy(frontend, backend, capture), do: call(:proxy, [frontend, backend, capture])

  def proxy_steerable(frontend, backend, capture, control),
    do: call(:proxy_steerable, [frontend, backend, capture, control])

  def has(capability), do: call(:has, [capability])
  def curve_keypair, do: call(:curve_keypair, [])
  def curve_public(secret), do: call(:curve_public, [secret])
  def subscribe(socket, prefix), do: call(:subscribe, [socket, prefix])
  def unsubscribe(socket, prefix), do: call(:unsubscribe, [socket, prefix])
  def join(socket, group), do: call(:join, [socket, group])
  def leave(socket, group), do: call(:leave, [socket, group])
  def send_group(socket, group, body), do: call(:send_group, [socket, group, body])
  def close(socket), do: call(:close, [socket])
  def close(socket, linger), do: call(:close, [socket, linger])

  def wait_connected(socket, min_peers, timeout),
    do: call(:wait_connected, [socket, min_peers, timeout])

  def wait_subscribed(socket, min_subscriptions, timeout),
    do: call(:wait_subscribed, [socket, min_subscriptions, timeout])

  def setsockopt(socket, option, value), do: call(:setsockopt, [socket, option, value])
  def getsockopt(socket, option), do: call(:getsockopt, [socket, option])
  def socket_type(socket), do: call(:socket_type, [socket])

  def pair, do: call(:pair, [])
  def pub, do: call(:pub, [])
  def sub, do: call(:sub, [])
  def req, do: call(:req, [])
  def rep, do: call(:rep, [])
  def dealer, do: call(:dealer, [])
  def router, do: call(:router, [])
  def pull, do: call(:pull, [])
  def push, do: call(:push, [])
  def xpub, do: call(:xpub, [])
  def xsub, do: call(:xsub, [])
  def stream, do: call(:stream, [])
  def server, do: call(:server, [])
  def client, do: call(:client, [])
  def radio, do: call(:radio, [])
  def dish, do: call(:dish, [])
  def gather, do: call(:gather, [])
  def scatter, do: call(:scatter, [])
  def peer, do: call(:peer, [])
  def channel, do: call(:channel, [])

  def pollin, do: call(:pollin, [])
  def pollout, do: call(:pollout, [])
  def pollerr, do: call(:pollerr, [])
  def sndmore, do: call(:sndmore, [])
  def noblock, do: call(:noblock, [])
  def dontwait, do: call(:dontwait, [])
  def affinity, do: call(:affinity, [])
  def identity, do: call(:identity, [])
  def routing_id, do: call(:routing_id, [])
  def subscribe_opt, do: call(:subscribe_opt, [])
  def unsubscribe_opt, do: call(:unsubscribe_opt, [])
  def rcvmore, do: call(:rcvmore, [])
  def fd, do: call(:fd, [])
  def events, do: call(:events, [])
  def type, do: call(:type, [])
  def backlog, do: call(:backlog, [])
  def linger, do: call(:linger, [])
  def reconnect_ivl, do: call(:reconnect_ivl, [])
  def reconnect_ivl_max, do: call(:reconnect_ivl_max, [])
  def maxmsgsize, do: call(:maxmsgsize, [])
  def sndhwm, do: call(:sndhwm, [])
  def rcvhwm, do: call(:rcvhwm, [])
  def rcvtimeo, do: call(:rcvtimeo, [])
  def sndtimeo, do: call(:sndtimeo, [])
  def router_mandatory, do: call(:router_mandatory, [])
  def tcp_keepalive, do: call(:tcp_keepalive, [])
  def tcp_keepalive_cnt, do: call(:tcp_keepalive_cnt, [])
  def tcp_keepalive_idle, do: call(:tcp_keepalive_idle, [])
  def tcp_keepalive_intvl, do: call(:tcp_keepalive_intvl, [])
  def sndbuf, do: call(:sndbuf, [])
  def rcvbuf, do: call(:rcvbuf, [])
  def conflate, do: call(:conflate, [])
  def handshake_ivl, do: call(:handshake_ivl, [])
  def heartbeat_ivl, do: call(:heartbeat_ivl, [])
  def heartbeat_ttl, do: call(:heartbeat_ttl, [])
  def heartbeat_timeout, do: call(:heartbeat_timeout, [])
  def reconnect_stop, do: call(:reconnect_stop, [])
  def immediate, do: call(:immediate, [])
  def ipv6, do: call(:ipv6, [])
  def ipv4only, do: call(:ipv4only, [])
  def rate, do: call(:rate, [])
  def connect_timeout, do: call(:connect_timeout, [])
  def xpub_verbose, do: call(:xpub_verbose, [])
  def probe_router, do: call(:probe_router, [])
  def req_correlate, do: call(:req_correlate, [])
  def req_relaxed, do: call(:req_relaxed, [])
  def router_handover, do: call(:router_handover, [])
  def tcp_accept_filter, do: call(:tcp_accept_filter, [])
  def tcp_maxrt, do: call(:tcp_maxrt, [])
  def multicast_hops, do: call(:multicast_hops, [])
  def recovery_ivl, do: call(:recovery_ivl, [])
  def zap_domain, do: call(:zap_domain, [])
  def mechanism, do: call(:mechanism, [])
  def plain_server, do: call(:plain_server, [])
  def plain_username, do: call(:plain_username, [])
  def plain_password, do: call(:plain_password, [])
  def curve_server, do: call(:curve_server, [])
  def curve_publickey, do: call(:curve_publickey, [])
  def curve_secretkey, do: call(:curve_secretkey, [])
  def curve_serverkey, do: call(:curve_serverkey, [])
  def last_endpoint, do: call(:last_endpoint, [])
  def omq_on_mute, do: call(:omq_on_mute, [])
  def omq_compression_level, do: call(:omq_compression_level, [])
  def omq_compression_dict, do: call(:omq_compression_dict, [])
  def omq_compression_auto_train, do: call(:omq_compression_auto_train, [])
  def omq_workload_profile, do: call(:omq_workload_profile, [])

  defp call(function, args), do: :erlang.apply(:omq, function, args)
end
