[package]
name = "zguide-08-majordomo"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
omq-tokio = { version = "0.21.2", path = "../../../omq-tokio" }
tokio = { version = "1", features = ["rt", "macros", "time"] }
bytes = "1"

[[bin]]
name = "zg08_broker"
path = "broker.rs"

[[bin]]
name = "zg08_worker"
path = "worker.rs"

[[bin]]
name = "zg08_client"
path = "client.rs"



[lints]
workspace = true
