/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeContext {
  constructor(options?: NativeContextOptions | undefined | null)
  socket(socketType: string, options?: NativeSocketOptions | undefined | null): NativeSocket
  close(): void
  shareKey(): string
}

export declare class NativeSocket {
  bind(endpoint: string): Promise<string>
  connect(endpoint: string): Promise<void>
  unbind(endpoint: string): Promise<void>
  disconnect(endpoint: string): Promise<void>
  send(parts: Array<Uint8Array>): Promise<void>
  sendSync(parts: Array<Uint8Array>): void
  recv(): Promise<Array<Buffer>>
  recvSync(): Array<Buffer>
  recvTimeout(timeoutMs: number): Promise<Array<Buffer> | null>
  tryRecv(): Array<Buffer> | null
  waitConnectedSync(minPeers: number, timeoutMs: number): number
  recvManySync(max: number, timeoutMs?: number | undefined | null): Array<Array<Buffer>>
  subscribe(prefix: Uint8Array): Promise<void>
  unsubscribe(prefix: Uint8Array): Promise<void>
  join(group: Uint8Array): Promise<void>
  leave(group: Uint8Array): Promise<void>
  close(): void
}

export declare function curveKeypair(): NativeCurveKeypair

export declare function curvePublic(secretKey: string): string

export declare function nativeContextFromShareKey(shareKey: string): NativeContext

export interface NativeContextOptions {
  ioThreads?: number
}

export interface NativeCurveKeypair {
  publicKey: string
  secretKey: string
}

export interface NativeCurveOptions {
  serverKey?: string
  publicKey: string
  secretKey: string
  server?: boolean
}

export interface NativePlainOptions {
  username: string
  password: string
  server?: boolean
}

export interface NativeSocketOptions {
  identity?: Uint8Array
  sendHighWaterMark?: number
  receiveHighWaterMark?: number
  reconnectInitialDelayMs?: number
  reconnectMaxDelayMs?: number
  lingerMs?: number
  routerMandatory?: boolean
  conflate?: boolean
  xpubNodrop?: boolean
  onMute?: string
  workloadProfile?: string
  compressionDictionary?: Uint8Array
  plain?: NativePlainOptions
  curve?: NativeCurveOptions
}
