/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeContext {
  constructor(options?: NativeContextOptions | undefined | null)
  socket(socketType: string, options?: NativeSocketOptions | undefined | null): NativeSocket
  close(): void
  shareKey(): string
}

export declare class NativeSocket {
  bind(endpoint: string): string
  connect(endpoint: string): void
  unbind(endpoint: string): void
  disconnect(endpoint: string): void
  send(parts: Array<Uint8Array>): void
  sendAsync(parts: Array<Uint8Array>): Promise<void>
  sendRoutedAsync(parts: Array<Uint8Array>, routingId: number): Promise<void>
  trySend(parts: Array<Uint8Array>): boolean
  trySendRouted(parts: Array<Uint8Array>, routingId: number): boolean
  trySendOne(payload: Uint8Array): boolean
  trySendBuffer(payload: Buffer): boolean
  sendSync(parts: Array<Uint8Array>): void
  sendRoutedSync(parts: Array<Uint8Array>, routingId: number): void
  sendOneSync(payload: Uint8Array): void
  sendBufferSync(payload: Buffer): void
  sendGroupSync(group: Uint8Array, payload: Uint8Array): void
  recv(): Array<Uint8Array>
  recvSync(): Array<Uint8Array>
  recvRawSync(): Uint8Array | Array<Uint8Array>
  recvRaw(cancelId?: number | undefined | null): Promise<Uint8Array | Array<Uint8Array>>
  recvRouted(cancelId?: number | undefined | null): Promise<NativeRoutedMessage>
  cancelRecv(cancelId: number): void
  recvTimeout(timeoutMs: number): Array<Uint8Array> | null
  tryRecv(): Array<Uint8Array> | null
  tryRecvRaw(): Uint8Array | Array<Uint8Array> | null
  recvRoutedSync(): NativeRoutedMessage
  tryRecvRouted(): NativeRoutedMessage | null
  recvRawManySync(max: number): Array<Uint8Array | Array<Uint8Array>>
  recvPackedManySync(max: number): NativePackedMessages
  tryRecvRawManySync(max: number): Array<Uint8Array | Array<Uint8Array>>
  tryRecvPackedManySync(max: number): NativePackedMessages
  waitConnectedSync(minPeers: number, timeoutMs: number): number
  recvManySync(max: number, timeoutMs?: number | undefined | null): Array<Array<Uint8Array>>
  recvRoutedManySync(max: number, timeoutMs?: number | undefined | null): Array<NativeRoutedMessage>
  subscribe(prefix: Uint8Array): void
  unsubscribe(prefix: Uint8Array): void
  join(group: Uint8Array): void
  leave(group: Uint8Array): void
  close(): void
}

export declare function curveKeypair(): NativeCurveKeypair

export declare function curvePublic(secretKey: string): string

export declare function nativeContextFromShareKey(shareKey: string): NativeContext

export interface NativeContextOptions {
  ioThreads?: number
}

export interface NativeCurveKeypair {
  publicKey: string
  secretKey: string
}

export interface NativeCurveOptions {
  serverKey?: string
  publicKey: string
  secretKey: string
  server?: boolean
}

export interface NativePackedMessages {
  data: Uint8Array
  partOffsets: Uint32Array
  partLengths: Uint32Array
  messageParts: Uint32Array
}

export interface NativePlainOptions {
  username: string
  password: string
  server?: boolean
}

export interface NativeRoutedMessage {
  parts: Array<Uint8Array>
  routingId: number
}

export interface NativeSocketOptions {
  identity?: Uint8Array
  sendHighWaterMark?: number
  receiveHighWaterMark?: number
  reconnectInitialDelayMs?: number
  reconnectMaxDelayMs?: number
  lingerMs?: number
  routerMandatory?: boolean
  conflate?: boolean
  xpubNodrop?: boolean
  onMute?: string
  workloadProfile?: string
  compressionDictionary?: Uint8Array
  plain?: NativePlainOptions
  curve?: NativeCurveOptions
}
